name: Google Analytics
version: 2.0.0 Beta 2
description: Add Google Analytics to Statamic V2
url: https://github.com/jrc9designstudio/statamic-google-analytics
developer: JRC9 Design Studio
developer_url: https://github.com/jrc9designstudio
